0901/hws/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
]

0901/hws/crud/articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()

    def __str__(self):
        return self.title

0901/hws/crud/articles/views.py
from django.shortcuts import render
from .models import Article

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


def new(request):
    return render(request, 'articles/new.html')


def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()

    return render(request, 'articles/create.html')
    

0901/hws/crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
  <h1>CREATE</h1>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock content %}

0901/hws/crud/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:new' %}">NEW</a>
  <br>
  {% for article in articles %}
    <hr>
    <p class="title">제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
  {% endfor %}
{% endblock content %}

0901/hws/crud/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block content %}
  <h1>NEW</h1>
  <br>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE : </label>
    <input type="text" id="title" name="title">
    <label for="content">CONTENT : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit" value="작성">
  </form>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock content %}